"""Hard-coded Supplier Site → (Location, Accounts Incharge) mapping.
1 100+ entries maintained by the RDC team. Custom additions live in
mappings.json (via the Manage Mappings dialog).
"""

SITE_MAPPING: dict[str, tuple[str, str]] = {
    'AEROCITY-CAPEX': ('CAPEX', 'Khushi'),
    'AHEMDABAD': ('GUJARAT', 'Dinesh Sir'),
    'AHEMEDABAD': ('GUJARAT', 'Dinesh Sir'),
    'AHM-GIFT CITY': ('GUJARAT', 'Dinesh Sir'),
    'AHM-GIFTCITY': ('GUJARAT', 'Dinesh Sir'),
    'AHM-SANAND': ('GUJARAT', 'Dinesh Sir'),
    'AHMEDABAD': ('GUJARAT', 'Dinesh Sir'),
    'AHMEDABAD -1': ('GUJARAT', 'Dinesh Sir'),
    'AHMEDABAD SHELA': ('GUJARAT', 'Dinesh Sir'),
    'AHMEDABAD TELAV': ('GUJARAT', 'Dinesh Sir'),
    'AHMEDABAD-1': ('GUJARAT', 'Dinesh Sir'),
    'AHMEDABAD-I': ('GUJARAT', 'Dinesh Sir'),
    'AHMEDABAD-SANAN': ('GUJARAT', 'Dinesh Sir'),
    'AHMEDABAD-SHELA': ('GUJARAT', 'Dinesh Sir'),
    'AHMEDABAD1': ('GUJARAT', 'Dinesh Sir'),
    'AMBALA-CAPEX': ('CAPEX', 'Khushi'),
    'AMBALAMUGAL-CAP': ('CAPEX', 'Khushi'),
    'AMBUJA-CAPEX': ('CAPEX', 'Khushi'),
    'AN1-CAPEX': ('CAPEX', 'Khushi'),
    'ANDHERI-CAPEX': ('CAPEX', 'Khushi'),
    'AURANGABAD': ('SAMBHAJI NAGAR', 'Pramod Sir'),
    'AYODHYA': ('UTTAR PRADESH', 'Dharampal Sir'),
    'AYODHYA-CAPEX': ('CAPEX', 'Khushi'),
    'Ahmedabad Sanan': ('GUJARAT', 'Dinesh Sir'),
    'Aurangabad-2': ('SAMBHAJI NAGAR', 'Pramod Sir'),
    'BAN4-CAPEX': ('CAPEX', 'Khushi'),
    'BANG1-CAPEX': ('CAPEX', 'Khushi'),
    'BANG2-CAPEX': ('CAPEX', 'Khushi'),
    'BANG3-CAPEX': ('CAPEX', 'Khushi'),
    'BANG4-CAPEX': ('CAPEX', 'Khushi'),
    'BANG5-CAPEX': ('CAPEX', 'Khushi'),
    'BANG8-CAPEX': ('CAPEX', 'Khushi'),
    'BANGALORE': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE - 1': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE - 2': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE - 3': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE - 4': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE - 5': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE -14': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE -3': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE 1': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE 2': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE 4': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE 7': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE- 1': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE- 2': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE- 3': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-1': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-10': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-11': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-12': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-13': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-14': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-15': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-16': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-17': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-18': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-19': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-2': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-20': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-21': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-3': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-4': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-4-CSR': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-5': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-5-CSR': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-6': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-6 CAP': ('CAPEX', 'Khushi'),
    'BANGALORE-7': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-8': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-8-CAP': ('CAPEX', 'Khushi'),
    'BANGALORE-9': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE-ANJAN': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGALORE1-CAPE': ('CAPEX', 'Khushi'),
    'BANGAORE-1': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGLORE-3': ('BANGALORE', 'Elaiyaraja Sir'),
    'BANGLORE-8-CAP': ('CAPEX', 'Khushi'),
    'BARH-BIHAR-CAPE': ('CAPEX', 'Khushi'),
    'BARMER-CAPEX': ('CAPEX', 'Khushi'),
    'BELGAUM': ('BANGALORE', 'Elaiyaraja Sir'),
    'BELGAUM CAPEX': ('CAPEX', 'Khushi'),
    'BELGAUM-CAPEX': ('CAPEX', 'Khushi'),
    'BELGUAM': ('BANGALORE', 'Elaiyaraja Sir'),
    'BG-1-CAPEX': ('CAPEX', 'Khushi'),
    'BG-11-CSR': ('BANGALORE', 'Elaiyaraja Sir'),
    'BG-13-CSR': ('BANGALORE', 'Elaiyaraja Sir'),
    'BG-14-CSR': ('BANGALORE', 'Elaiyaraja Sir'),
    'BG-2-CAPEX': ('CAPEX', 'Khushi'),
    'BG-2-CSR': ('BANGALORE', 'Elaiyaraja Sir'),
    'BG-3 CAPEX': ('CAPEX', 'Khushi'),
    'BG-3-CAPEX': ('CAPEX', 'Khushi'),
    'BG-3-CSR': ('BANGALORE', 'Elaiyaraja Sir'),
    'BG-4-CAPEX': ('CAPEX', 'Khushi'),
    'BG-4-CSR': ('BANGALORE', 'Elaiyaraja Sir'),
    'BG-5-CAPEX': ('CAPEX', 'Khushi'),
    'BG-6 CAPEX': ('CAPEX', 'Khushi'),
    'BG-6-CAPEX': ('CAPEX', 'Khushi'),
    'BG-6-CSR': ('BANGALORE', 'Elaiyaraja Sir'),
    'BG-8-CAPEX': ('CAPEX', 'Khushi'),
    'BG-Anjanapura': ('BANGALORE', 'Elaiyaraja Sir'),
    'BG-Lodha': ('BANGALORE', 'Elaiyaraja Sir'),
    'BG-Lodha Heaven': ('BANGALORE', 'Elaiyaraja Sir'),
    'BG-Sadahali': ('BANGALORE', 'Elaiyaraja Sir'),
    'BG-Tumkur Road': ('BANGALORE', 'Elaiyaraja Sir'),
    'BG2-CAPE': ('CAPEX', 'Khushi'),
    'BG2-CAPEX': ('CAPEX', 'Khushi'),
    'BGLORE-1-CAPEX': ('CAPEX', 'Khushi'),
    'BGLORE-5-CAPEX': ('CAPEX', 'Khushi'),
    'BHANKROTA-CAPEX': ('CAPEX', 'Khushi'),
    'BHEL - CAPEX': ('CAPEX', 'Khushi'),
    'BHEL BIHAR-CAPE': ('CAPEX', 'Khushi'),
    'BHEL BIHARCAPEX': ('CAPEX', 'Khushi'),
    'BHEL-BHILAI': ('CHHATTISGARH', 'Makrand Sir'),
    'BHEL-BIHAR-CAPE': ('CAPEX', 'Khushi'),
    'BHEL-BIHARCAPEX': ('CAPEX', 'Khushi'),
    'BHEL-PATNA': ('BIHAR', 'Sapan Sir'),
    'BHEL-SAGARDIGH': ('WEST BENGAL', 'Sapan Sir'),
    'BHEL-SAGARDIGH.': ('WEST BENGAL', 'Sapan Sir'),
    'BHEL-SAGARDIGHI': ('WEST BENGAL', 'Sapan Sir'),
    'BHELBHIHAR-CAPE': ('CAPEX', 'Khushi'),
    'BHELBIHAR-CAPEX': ('CAPEX', 'Khushi'),
    'BHILAI': ('CHHATTISGARH', 'Makrand Sir'),
    'BHILAI-BHEL': ('CHHATTISGARH', 'Makrand Sir'),
    'BHILAI-CAPEX': ('CAPEX', 'Khushi'),
    'BHILLAI CAPEX': ('CAPEX', 'Khushi'),
    'BHILLAI-CAPEX': ('CAPEX', 'Khushi'),
    'BHOIWADA-CAPEX': ('CAPEX', 'Khushi'),
    'BHOPAL': ('BHOPAL', 'Makrand Sir'),
    'BHOPAL-1': ('BHOPAL', 'Makrand Sir'),
    'BHOPAL-2': ('BHOPAL', 'Makrand Sir'),
    'BHOPAL-CAPEX': ('CAPEX', 'Khushi'),
    'BHOPAL-CSR': ('BHOPAL', 'Makrand Sir'),
    'BHOPAL-DIPDI': ('BHOPAL', 'Makrand Sir'),
    'BHOPAL-JABALPUR': ('BHOPAL', 'Makrand Sir'),
    'BHOPAL-MUGLIYA': ('BHOPAL', 'Makrand Sir'),
    'BHOPAL-MUNGALIY': ('BHOPAL', 'Makrand Sir'),
    'BHR-Captive': ('CAPEX', 'Khushi'),
    'BHU-CAPEX': ('CAPEX', 'Khushi'),
    'BHUB-CAPEX': ('CAPEX', 'Khushi'),
    'BHUBANESHWAR': ('ODISHA + RANCHI', 'Manas Sir'),
    'BHUBANESHWAR-2': ('ODISHA + RANCHI', 'Manas Sir'),
    'BHUBANESW-CAPEX': ('CAPEX', 'Khushi'),
    'BHUBANESWAR': ('ODISHA + RANCHI', 'Manas Sir'),
    'BHUBANESWAR-1': ('ODISHA + RANCHI', 'Manas Sir'),
    'BHUBANESWAR-2': ('ODISHA + RANCHI', 'Manas Sir'),
    'BHUBANESWAR-CAP': ('CAPEX', 'Khushi'),
    'BHUBANESWAR-CSR': ('ODISHA + RANCHI', 'Manas Sir'),
    'BHUBANESWAR-NOR': ('ODISHA + RANCHI', 'Manas Sir'),
    'BHUBANESWAR-PAH': ('ODISHA + RANCHI', 'Manas Sir'),
    'BHUBANESWER': ('ODISHA + RANCHI', 'Manas Sir'),
    'BHUBANEWHWAR': ('ODISHA + RANCHI', 'Manas Sir'),
    'BHUBNESHWAR': ('ODISHA + RANCHI', 'Manas Sir'),
    'BHUVENSWR-CAPEX': ('CAPEX', 'Khushi'),
    'BIHAR-BARH-CAPE': ('CAPEX', 'Khushi'),
    'BNG 11-CAPEX': ('CAPEX', 'Khushi'),
    'BNG LODHA-2': ('BANGALORE', 'Elaiyaraja Sir'),
    'BNG-3-CAPEX': ('CAPEX', 'Khushi'),
    'BNG11-CAPEX': ('CAPEX', 'Khushi'),
    'BNG12-CAPEX': ('CAPEX', 'Khushi'),
    'BNG13-CAPEX': ('CAPEX', 'Khushi'),
    'BNG14-CAPEX': ('CAPEX', 'Khushi'),
    'BNG15-CAPEX': ('CAPEX', 'Khushi'),
    'BNG16-CAPEX': ('CAPEX', 'Khushi'),
    'BNG17-CAPEX': ('CAPEX', 'Khushi'),
    'BNG18': ('BANGALORE', 'Elaiyaraja Sir'),
    'BNG18-CAPEX': ('CAPEX', 'Khushi'),
    'BNG19-CAPEX': ('CAPEX', 'Khushi'),
    'BNG2-CAPEX': ('CAPEX', 'Khushi'),
    'BNG20-CAPEX': ('CAPEX', 'Khushi'),
    'BNG3-CAPEX': ('CAPEX', 'Khushi'),
    'BNG4-CAPEX': ('CAPEX', 'Khushi'),
    'BNG5-CAPEX': ('CAPEX', 'Khushi'),
    'BNG6-CAPEX': ('CAPEX', 'Khushi'),
    'BNG8-CAPEX': ('CAPEX', 'Khushi'),
    'BNG9-CAPEX': ('CAPEX', 'Khushi'),
    'BOMBAY-CAPEX': ('CAPEX', 'Khushi'),
    'BU2 CAPEX': ('CAPEX', 'Khushi'),
    'BU2-CAPEX': ('CAPEX', 'Khushi'),
    'Bangalore 2-Cap': ('CAPEX', 'Khushi'),
    'Bangalore 3-Cap': ('CAPEX', 'Khushi'),
    'Bangalore 5-Cap': ('CAPEX', 'Khushi'),
    'Bangalore 8-Cap': ('CAPEX', 'Khushi'),
    'Bangalore-Sadah': ('BANGALORE', 'Elaiyaraja Sir'),
    'Banglore-Lodha': ('BANGALORE', 'Elaiyaraja Sir'),
    'Belgaum Dalmia': ('BANGALORE', 'Elaiyaraja Sir'),
    'Bihar': ('BIHAR', 'Sapan Sir'),
    'C12-CAPEX': ('CAPEX', 'Khushi'),
    'C13-CAPEX': ('CAPEX', 'Khushi'),
    'CHE-MADHAVARAM': ('CHENNAI', 'Veerabagu Sir'),
    'CHE-MEDAVAKKAM': ('CHENNAI', 'Veerabagu Sir'),
    'CHEN-2-CAPEX': ('CAPEX', 'Khushi'),
    'CHENNA1-1': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI -5': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI 1': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI 2': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI 3': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI 4': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI 5': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-1': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-1 CAPEX': ('CAPEX', 'Khushi'),
    'CHENNAI-1 CSR': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-1-CAPEX': ('CAPEX', 'Khushi'),
    'CHENNAI-1-CSR': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-11': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-12': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-13': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-14': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-15': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-2': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-2 CAPEX': ('CAPEX', 'Khushi'),
    'CHENNAI-2-CAPEX': ('CAPEX', 'Khushi'),
    'CHENNAI-3': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-3-CAPEX': ('CAPEX', 'Khushi'),
    'CHENNAI-4': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-4-CAPEX': ('CAPEX', 'Khushi'),
    'CHENNAI-5': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-5 CAPEX': ('CAPEX', 'Khushi'),
    'CHENNAI-5-CAPEX': ('CAPEX', 'Khushi'),
    'CHENNAI-6': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-6-CAPEX': ('CAPEX', 'Khushi'),
    'CHENNAI-7': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-9': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-CAPEX': ('CAPEX', 'Khushi'),
    'CHENNAI-CSR': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-MEDAVAK': ('CHENNAI', 'Veerabagu Sir'),
    'CHENNAI-POONAMA': ('CHENNAI', 'Veerabagu Sir'),
    'CHN1-CAPEX': ('CAPEX', 'Khushi'),
    'CHN10-CAPEX': ('CAPEX', 'Khushi'),
    'CHN11-CAPEX': ('CAPEX', 'Khushi'),
    'CHN12-CAPEX': ('CAPEX', 'Khushi'),
    'CHN13-CAPEX': ('CAPEX', 'Khushi'),
    'CHN14-CAPEX': ('CAPEX', 'Khushi'),
    'CHN2-CAPEX': ('CAPEX', 'Khushi'),
    'CHN3-CAPEX': ('CAPEX', 'Khushi'),
    'CHN4-CAPEX': ('CAPEX', 'Khushi'),
    'CHN5-CAPEX': ('CAPEX', 'Khushi'),
    'CHN6-CAPEX': ('CAPEX', 'Khushi'),
    'CHN7-CAPEX': ('CAPEX', 'Khushi'),
    'CHN8-CAPEX': ('CAPEX', 'Khushi'),
    'CHN9-CAPEX': ('CAPEX', 'Khushi'),
    'CHT-RAIPUR': ('CHHATTISGARH', 'Makrand Sir'),
    'CM2-CAPEX': ('CAPEX', 'Khushi'),
    'COIMB-CAPEX': ('CAPEX', 'Khushi'),
    'COIMBATORE': ('COIMBATORE + TRICHY', 'Sulaiman Sir'),
    'COIMBATORE- 1': ('COIMBATORE + TRICHY', 'Sulaiman Sir'),
    'COIMBATORE-1': ('COIMBATORE + TRICHY', 'Sulaiman Sir'),
    'COIMBATORE-2': ('COIMBATORE + TRICHY', 'Sulaiman Sir'),
    'COIMBATORE-CAPE': ('CAPEX', 'Khushi'),
    'CUTTACK-CAPEX': ('CAPEX', 'Khushi'),
    'CUTTACK-GDCL': ('ODISHA + RANCHI', 'Manas Sir'),
    'CUTTACK-JAG': ('ODISHA + RANCHI', 'Manas Sir'),
    'CUTTACK-JAGATPU': ('ODISHA + RANCHI', 'Manas Sir'),
    'CUTTAK-CAPEX': ('CAPEX', 'Khushi'),
    'CUTTUCK-CAPEX': ('CAPEX', 'Khushi'),
    'Chennai 1-Capex': ('CAPEX', 'Khushi'),
    'Chennai 2-Capex': ('CAPEX', 'Khushi'),
    'Chennai 3-Capex': ('CAPEX', 'Khushi'),
    'Chennai 4-Capex': ('CAPEX', 'Khushi'),
    'DALMIA-CAPEX': ('CAPEX', 'Khushi'),
    'DALMIA-LANKA': ('ASSAM', 'Sapan Sir'),
    'DEHRADUN': ('UTTARAKHAND', 'Dharampal Sir'),
    'DEHRADUN-CAPEX': ('CAPEX', 'Khushi'),
    'DELHI': ('NCR + Delhi', 'Dharampal Sir'),
    'DELHI  GHEVRA': ('NCR + Delhi', 'Dharampal Sir'),
    'DELHI AEROCITY': ('NCR + Delhi', 'Dharampal Sir'),
    'DELHI GHEVRA': ('NCR + Delhi', 'Dharampal Sir'),
    'DELHI RANI KHER': ('NCR + Delhi', 'Dharampal Sir'),
    'DELHI RANIKHERA': ('NCR + Delhi', 'Dharampal Sir'),
    'DELHI-RANIKHERA': ('NCR + Delhi', 'Dharampal Sir'),
    'DELHI-VINTA': ('NCR + Delhi', 'Dharampal Sir'),
    'DELHI-VINTA REA': ('NCR + Delhi', 'Dharampal Sir'),
    'DEONAR': ('MUMBAI', 'Haresh Sir'),
    'DEONAR-CAP': ('CAPEX', 'Khushi'),
    'DEONAR-CAPEX': ('CAPEX', 'Khushi'),
    'DERABASSI': ('PUNJAB', 'Mukesh Sir'),
    'DERABASSI-CAPEX': ('CAPEX', 'Khushi'),
    'DIGHI 14-CAPEX': ('CAPEX', 'Khushi'),
    'DIGHI14-CAPEX': ('CAPEX', 'Khushi'),
    'DOMBIVALI-CAPEX': ('CAPEX', 'Khushi'),
    'DUMAD-CAPEX': ('CAPEX', 'Khushi'),
    'DURG': ('CHHATTISGARH', 'Makrand Sir'),
    'DURG-CAPEX': ('CAPEX', 'Khushi'),
    'Daulatabad': ('NCR + Delhi', 'Dharampal Sir'),
    'Delh-Aerocity': ('NCR + Delhi', 'Dharampal Sir'),
    'Delhi-Aerocity': ('NCR + Delhi', 'Dharampal Sir'),
    'Delhi-Ghevra': ('NCR + Delhi', 'Dharampal Sir'),
    'EDAYAR': ('KERALA', "Aswathy Ma'am"),
    'EDAYAR-CAPEX': ('CAPEX', 'Khushi'),
    'EDYAR-CAPEX': ('CAPEX', 'Khushi'),
    'FARAKKA': ('WEST BENGAL', 'Sapan Sir'),
    'FARAKKA-CAPEX': ('CAPEX', 'Khushi'),
    'FARAKKA-GDCL': ('WEST BENGAL', 'Sapan Sir'),
    'FARIDABAD': ('NCR + Delhi', 'Dharampal Sir'),
    'FARIDABAD 1': ('NCR + Delhi', 'Dharampal Sir'),
    'FARIDABAD MATHU': ('NCR + Delhi', 'Dharampal Sir'),
    'FARIDABAD-1': ('NCR + Delhi', 'Dharampal Sir'),
    'FARIDABAD-2': ('NCR + Delhi', 'Dharampal Sir'),
    'FARIDABAD-CAPEX': ('CAPEX', 'Khushi'),
    'FARIDABAD1': ('NCR + Delhi', 'Dharampal Sir'),
    'FR2-CAPEX': ('CAPEX', 'Khushi'),
    'GANDHINAGAR-GIF': ('GUJARAT', 'Dinesh Sir'),
    'GDCL JAJ-CAPEX': ('CAPEX', 'Khushi'),
    'GDCL JAJPUR': ('ODISHA + RANCHI', 'Manas Sir'),
    'GDCL-CAPEX': ('CAPEX', 'Khushi'),
    'GDCL-CUTTACK-CA': ('ODISHA + RANCHI', 'Manas Sir'),
    'GDCL-JAJ-CAPEX': ('CAPEX', 'Khushi'),
    'GHATAMPUR': ('UTTAR PRADESH', 'Dharampal Sir'),
    'GHATAMPUR-CAPEX': ('CAPEX', 'Khushi'),
    'GHAZIABAD': ('UTTAR PRADESH', 'Dharampal Sir'),
    'GHAZIABAD(NIR)': ('UTTAR PRADESH', 'Dharampal Sir'),
    'GHEVRA-CAPEX': ('CAPEX', 'Khushi'),
    'GIFTCITY-CAPEX': ('CAPEX', 'Khushi'),
    'GJ3-CAPEX': ('CAPEX', 'Khushi'),
    'GJ4-CAPEX': ('CAPEX', 'Khushi'),
    'GJ5-CAPEX': ('CAPEX', 'Khushi'),
    'GN2-CAPEX': ('CAPEX', 'Khushi'),
    'GN3-CAPEX': ('CAPEX', 'Khushi'),
    'GOA': ('GOA', 'Makrand Sir'),
    'GOA -VERNA': ('GOA', 'Makrand Sir'),
    'GOA -VERNA SOUT': ('GOA', 'Makrand Sir'),
    'GOA-CAPEX': ('CAPEX', 'Khushi'),
    'GOA-DLF': ('GOA', 'Makrand Sir'),
    'GOA-DLF CAPEX': ('CAPEX', 'Khushi'),
    'GOA-PHONDA': ('GOA', 'Makrand Sir'),
    'GOA-PONDA': ('GOA', 'Makrand Sir'),
    'GOA-VERNA': ('GOA', 'Makrand Sir'),
    'GOA2-CAPEX': ('CAPEX', 'Khushi'),
    'GOA4-CAPEX': ('CAPEX', 'Khushi'),
    'GODREJ-CAPEX': ('CAPEX', 'Khushi'),
    'GORAKHPUR': ('UTTAR PRADESH', 'Dharampal Sir'),
    'GORAKHPUR-CAPEX': ('CAPEX', 'Khushi'),
    'GOREGAON-CAPEX': ('CAPEX', 'Khushi'),
    'GR NOIDA-CAPEX': ('CAPEX', 'Khushi'),
    'GR-NOIDA-CAPEX': ('CAPEX', 'Khushi'),
    'GR. NODIA CAPEX': ('CAPEX', 'Khushi'),
    'GR.NOIDA': ('NCR + Delhi', 'Dharampal Sir'),
    'GR.NOIDA CAPEX': ('CAPEX', 'Khushi'),
    'GREATE NOIDA-G': ('NCR + Delhi', 'Dharampal Sir'),
    'GREATER  NOIDA': ('NCR + Delhi', 'Dharampal Sir'),
    'GREATER NOIDA': ('NCR + Delhi', 'Dharampal Sir'),
    'GREATER NOIDA G': ('NCR + Delhi', 'Dharampal Sir'),
    'GREATER NOIDA-1': ('NCR + Delhi', 'Dharampal Sir'),
    'GREATER NOIDA-C': ('NCR + Delhi', 'Dharampal Sir'),
    'GREATER NOIDA-G': ('NCR + Delhi', 'Dharampal Sir'),
    'GRNOIDA- CAPEX': ('CAPEX', 'Khushi'),
    'GRNOIDA-CAPEX': ('CAPEX', 'Khushi'),
    'GU3-CAPEX': ('CAPEX', 'Khushi'),
    'GU4-CAPEX': ('CAPEX', 'Khushi'),
    'GU5 -CAPEX': ('CAPEX', 'Khushi'),
    'GU5-CAPEX': ('CAPEX', 'Khushi'),
    'GU6-CAPEX': ('CAPEX', 'Khushi'),
    'GU7-CAPEX': ('CAPEX', 'Khushi'),
    'GU8-CAPEX': ('CAPEX', 'Khushi'),
    'GU9-CAPEX': ('CAPEX', 'Khushi'),
    'GUJ- VADODARA': ('GUJARAT', 'Dinesh Sir'),
    'GUJ-GIFTCITY': ('GUJARAT', 'Dinesh Sir'),
    'GUJ-Gift City': ('GUJARAT', 'Dinesh Sir'),
    'GUJ-Hazira Comm': ('GUJARAT', 'Dinesh Sir'),
    'GUJ-Icchapore': ('GUJARAT', 'Dinesh Sir'),
    'GUJ-MUNDRA': ('GUJARAT', 'Dinesh Sir'),
    'GUJ-TPL Hazira': ('GUJARAT', 'Dinesh Sir'),
    'GUJ-VADODARA': ('GUJARAT', 'Dinesh Sir'),
    'GUJ-VADODARA-DU': ('GUJARAT', 'Dinesh Sir'),
    'GUJ-VAPI': ('GUJARAT', 'Dinesh Sir'),
    'GUJARAT': ('GUJARAT', 'Dinesh Sir'),
    'GUJARAT-MUNDRA': ('GUJARAT', 'Dinesh Sir'),
    'GUJARAT-VAPI': ('GUJARAT', 'Dinesh Sir'),
    'GUR-CAPEX': ('CAPEX', 'Khushi'),
    'GURGAON': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON 1': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON BADSHAH': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON BADSHAP': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON CLASSIC': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON DAULTAB': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON GHATA': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON KHERKI': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON MAX': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON MAX-360': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON SHIKOH': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON SHIKOHP': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON-1': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON-BADHSHA': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON-CAPEX': ('CAPEX', 'Khushi'),
    'GURGAON-KHERKI': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON-M3M': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGAON1': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGOAN': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGOAN KHERKI': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGON': ('NCR + Delhi', 'Dharampal Sir'),
    'GURGON KHERKI': ('NCR + Delhi', 'Dharampal Sir'),
    'GURUGRAM - M3M': ('NCR + Delhi', 'Dharampal Sir'),
    'GURUGRAM M3M': ('NCR + Delhi', 'Dharampal Sir'),
    'GURUGRAM-KHERKI': ('NCR + Delhi', 'Dharampal Sir'),
    'GURUGRAM-M3M': ('NCR + Delhi', 'Dharampal Sir'),
    'GUWAHATI': ('ASSAM', 'Sapan Sir'),
    'GUWAHATI-1': ('ASSAM', 'Sapan Sir'),
    'GUWAHATI-2': ('ASSAM', 'Sapan Sir'),
    'GUWAHATI-3': ('ASSAM', 'Sapan Sir'),
    'GUWAHATI-Assam': ('ASSAM', 'Sapan Sir'),
    'GUWAHATI-CAPEX': ('CAPEX', 'Khushi'),
    'GW3-CAPEX': ('CAPEX', 'Khushi'),
    'Gorakhpur-UP': ('UTTAR PRADESH', 'Dharampal Sir'),
    'Gr.Noida-Capex': ('CAPEX', 'Khushi'),
    'Gurgaon-Classic': ('NCR + Delhi', 'Dharampal Sir'),
    'Gurgaon-Shikohp': ('NCR + Delhi', 'Dharampal Sir'),
    'Gurgoan - M3M': ('NCR + Delhi', 'Dharampal Sir'),
    'Gurgoan-Kherki': ('NCR + Delhi', 'Dharampal Sir'),
    'Gurgoan-Max': ('NCR + Delhi', 'Dharampal Sir'),
    'HA1-CAPEX': ('CAPEX', 'Khushi'),
    'HA2-CAPEX': ('CAPEX', 'Khushi'),
    'HARIDWAR': ('HARIDWAR', 'Dharampal Sir'),
    'HARIDWAR-CAPEX': ('CAPEX', 'Khushi'),
    'HAZIRA1-CAPEX': ('CAPEX', 'Khushi'),
    'HEAD OFFICE': ('HEAD OFFICE', 'Sneha'),
    'HEAD-OFFICE': ('HEAD OFFICE', 'Sneha'),
    'HO - CAPEX': ('CAPEX', 'Khushi'),
    'HO-CAPEX': ('CAPEX', 'Khushi'),
    'HO-MUMBAI': ('HEAD OFFICE', 'Sneha'),
    'HOOGHLY-1': ('WEST BENGAL', 'Sapan Sir'),
    'HOOGHLY-CAPEX': ('CAPEX', 'Khushi'),
    'HOSUR': ('BANGALORE', 'Elaiyaraja Sir'),
    'HOWRAH-CAPEX': ('CAPEX', 'Khushi'),
    'HYD-1': ('HYDERABAD', 'Rajesh Sir'),
    'HYD-1 CAPEX': ('CAPEX', 'Khushi'),
    'HYD-1-CAPEX': ('CAPEX', 'Khushi'),
    'HYD-1-CSR': ('HYDERABAD', 'Rajesh Sir'),
    'HYD-12 CAPEX': ('CAPEX', 'Khushi'),
    'HYD-13 CAPEX': ('CAPEX', 'Khushi'),
    'HYD-14 CAPEX': ('CAPEX', 'Khushi'),
    'HYD-17 CAPEX': ('CAPEX', 'Khushi'),
    'HYD-1CAPEX': ('CAPEX', 'Khushi'),
    'HYD-1CSR': ('HYDERABAD', 'Rajesh Sir'),
    'HYD-2 CAPEX': ('CAPEX', 'Khushi'),
    'HYD-2-CAPEX': ('CAPEX', 'Khushi'),
    'HYD-3  CAPEX': ('CAPEX', 'Khushi'),
    'HYD-3 CAPEX': ('CAPEX', 'Khushi'),
    'HYD-3-CAPEX': ('CAPEX', 'Khushi'),
    'HYD-4 CAPEX': ('CAPEX', 'Khushi'),
    'HYD-4-CAPEX': ('CAPEX', 'Khushi'),
    'HYD-4-CSR': ('HYDERABAD', 'Rajesh Sir'),
    'HYD-6-CAPEX': ('CAPEX', 'Khushi'),
    'HYD-7 CAPEX': ('CAPEX', 'Khushi'),
    'HYD-7-CAPEX': ('CAPEX', 'Khushi'),
    'HYD-8': ('HYDERABAD', 'Rajesh Sir'),
    'HYD-8 CAPEX': ('CAPEX', 'Khushi'),
    'HYD-8-CAPEX': ('CAPEX', 'Khushi'),
    'HYD-9-CAPEX': ('CAPEX', 'Khushi'),
    'HYD-Khanapur': ('HYDERABAD', 'Rajesh Sir'),
    'HYD-Kollur': ('HYDERABAD', 'Rajesh Sir'),
    'HYD-Satva': ('HYDERABAD', 'Rajesh Sir'),
    'HYD1-CAPEX': ('CAPEX', 'Khushi'),
    'HYD1-CAPEX.': ('CAPEX', 'Khushi'),
    'HYD10-CAPEX': ('CAPEX', 'Khushi'),
    'HYD14-CAPEX': ('CAPEX', 'Khushi'),
    'HYD15-CAPEX': ('CAPEX', 'Khushi'),
    'HYD16-CAPEX': ('CAPEX', 'Khushi'),
    'HYD17-CAPEX': ('CAPEX', 'Khushi'),
    'HYD2-CAPEX': ('CAPEX', 'Khushi'),
    'HYD3-CAPEX': ('CAPEX', 'Khushi'),
    'HYD4-CAPEX': ('CAPEX', 'Khushi'),
    'HYD6-CAPEX': ('CAPEX', 'Khushi'),
    'HYD7-CAPEX': ('CAPEX', 'Khushi'),
    'HYD8-CAPEX': ('CAPEX', 'Khushi'),
    'HYD9-CAP': ('CAPEX', 'Khushi'),
    'HYDERABAD': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD - 1': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD - 2': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD - I': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD -13': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD 1': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD 3': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD 4': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD 5': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD 6': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-1': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-1 CSR': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-1-CAP': ('CAPEX', 'Khushi'),
    'HYDERABAD-10': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-11': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-12': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-13': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-14': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-15': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-16': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-17': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-2': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-3': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-3 CSR': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-4': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-4CSR': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-5': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-6': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-6 CSR': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-7': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-7 CSR': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-8': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-9': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-PATAN': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-SATTV': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERABAD-VASAV': ('HYDERABAD', 'Rajesh Sir'),
    'HYDERBADAD-6': ('HYDERABAD', 'Rajesh Sir'),
    'HYDRABAD-1': ('HYDERABAD', 'Rajesh Sir'),
    'Hazira': ('GUJARAT', 'Dinesh Sir'),
    'Hazira Tata-Guj': ('GUJARAT', 'Dinesh Sir'),
    'Hazira-Sunvali': ('GUJARAT', 'Dinesh Sir'),
    'Hazira-Sunvali-': ('GUJARAT', 'Dinesh Sir'),
    'Hazira-Suvali': ('GUJARAT', 'Dinesh Sir'),
    'Hazira-Suvali P': ('GUJARAT', 'Dinesh Sir'),
    'Hyd-Medchal': ('HYDERABAD', 'Rajesh Sir'),
    'Hyderabad 2': ('HYDERABAD', 'Rajesh Sir'),
    'Hyderabad 3-Cap': ('CAPEX', 'Khushi'),
    'Hyderabad1-Cape': ('CAPEX', 'Khushi'),
    'ICHHAPUR-CAPEX': ('CAPEX', 'Khushi'),
    'ICHHAPURE': ('GUJARAT', 'Dinesh Sir'),
    'ICHHPORE-CAPEX': ('CAPEX', 'Khushi'),
    'IN-SANAWADIA': ('INDORE', 'Makrand Sir'),
    'IN-SANAWADIYA': ('MADHYA PRADESH', 'Makrand Sir'),
    'INDORE': ('INDORE', 'Makrand Sir'),
    'INDORE 2 - CAPE': ('CAPEX', 'Khushi'),
    'INDORE 2-CAPEX': ('CAPEX', 'Khushi'),
    'INDORE-1': ('INDORE', 'Makrand Sir'),
    'INDORE-BARDARI': ('INDORE', 'Makrand Sir'),
    'INDORE-BHARDARI': ('INDORE', 'Makrand Sir'),
    'INDORE-CAPEX': ('CAPEX', 'Khushi'),
    'INDORE-SANAWADI': ('INDORE', 'Makrand Sir'),
    'INDORE2-CAPEX': ('CAPEX', 'Khushi'),
    'ITD-MUNDRA': ('GUJARAT', 'Dinesh Sir'),
    'ITDHAZIRA': ('GUJARAT', 'Dinesh Sir'),
    'Indore-2': ('INDORE', 'Makrand Sir'),
    'JABALPUR CAPEX': ('CAPEX', 'Khushi'),
    'JABALPUR-CAPEX': ('CAPEX', 'Khushi'),
    'JAGATPUR-CAPEX': ('CAPEX', 'Khushi'),
    'JAGIROAD-CAPEX': ('CAPEX', 'Khushi'),
    'JAIPUR': ('NCR + Delhi', 'Dharampal Sir'),
    'JAIPUR 1': ('NCR + Delhi', 'Dharampal Sir'),
    'JAIPUR BHANKROT': ('NCR + Delhi', 'Dharampal Sir'),
    'JAIPUR-1': ('NCR + Delhi', 'Dharampal Sir'),
    'JAIPUR-BHANKROT': ('NCR + Delhi', 'Dharampal Sir'),
    'JAJPUR': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR - TATAST': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR GDCL': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR TATA2': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR-1': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR-CAPEX': ('CAPEX', 'Khushi'),
    'JAJPUR-EMAMI': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR-GDCL': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR-GDCL-CAP': ('CAPEX', 'Khushi'),
    'JAJPUR-JIN-CAPE': ('CAPEX', 'Khushi'),
    'JAJPUR-JMC TSL2': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR-JSL': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR-KEC': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR-TATA': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR-TATA 2': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR-TATA ST2': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR-TATA STE': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR-TATA2': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR-TATASTEE': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAJPUR-TSL2': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAMBE-CAPEX': ('CAPEX', 'Khushi'),
    'JAMMU': ('JAMMU', 'Mukesh Sir'),
    'JAMMU-CAPEX': ('CAPEX', 'Khushi'),
    'JAMMU-KATHUA': ('JAMMU', 'Mukesh Sir'),
    'JAMNAGAR': ('GUJARAT', 'Dinesh Sir'),
    'JAMNAGAR-CAPEX': ('CAPEX', 'Khushi'),
    'JAMSHDPUR-CAPEX': ('CAPEX', 'Khushi'),
    'JAMSHEDPUR': ('ODISHA + RANCHI', 'Manas Sir'),
    'JAMSHEDPUR-CAPE': ('CAPEX', 'Khushi'),
    'JEWAR UP': ('UTTAR PRADESH', 'Dharampal Sir'),
    'JEWAR-CAPEX': ('CAPEX', 'Khushi'),
    'JEWAR-UP': ('UTTAR PRADESH', 'Dharampal Sir'),
    'JK JAMMU': ('JAMMU', 'Mukesh Sir'),
    'JK-JAMMU': ('JAMMU', 'Mukesh Sir'),
    'JSL-CAPEX': ('CAPEX', 'Khushi'),
    'Jabalpur': ('MADHYA PRADESH', 'Makrand Sir'),
    'Jabalpur M.P': ('MADHYA PRADESH', 'Makrand Sir'),
    'Jaipur-2': ('NCR + Delhi', 'Dharampal Sir'),
    'Jajpur Tata2-Ca': ('ODISHA + RANCHI', 'Manas Sir'),
    'Jamnagar-Relian': ('GUJARAT', 'Dinesh Sir'),
    'KALYANI EXPRESS': ('WEST BENGAL', 'Sapan Sir'),
    'KALYANI EXPWAY': ('WEST BENGAL', 'Sapan Sir'),
    'KALYANI-CAPEX': ('CAPEX', 'Khushi'),
    'KANNUR-CAPEX': ('CAPEX', 'Khushi'),
    'KARJAT-CAPEX': ('CAPEX', 'Khushi'),
    'KATHUA - CAPEX': ('CAPEX', 'Khushi'),
    'KATHUA -CAPEX': ('CAPEX', 'Khushi'),
    'KATHUA-CAPEX': ('CAPEX', 'Khushi'),
    'KEC-JAJPUR': ('ODISHA + RANCHI', 'Manas Sir'),
    'KECCAPEX': ('CAPEX', 'Khushi'),
    'KER-Kochi 1 Edy': ('KERALA', "Aswathy Ma'am"),
    'KER-Kochi Ambal': ('KERALA', "Aswathy Ma'am"),
    'KER-Kottayam': ('KERALA', "Aswathy Ma'am"),
    'KER-TVM 1': ('KERALA', "Aswathy Ma'am"),
    'KER-TVM 2': ('KERALA', "Aswathy Ma'am"),
    'KER-TVM2': ('KERALA', "Aswathy Ma'am"),
    'KER-Trivandrum': ('KERALA', "Aswathy Ma'am"),
    'KER-Wayanad': ('KERALA', "Aswathy Ma'am"),
    'KERALA': ('KERALA', "Aswathy Ma'am"),
    'KERALA-TVM1': ('KERALA', "Aswathy Ma'am"),
    'KHALAPUR-CAPEX': ('CAPEX', 'Khushi'),
    'KHANDSA-CAPEX': ('CAPEX', 'Khushi'),
    'KHARGHAR-CAPEX': ('CAPEX', 'Khushi'),
    'KHARKHODA': ('NCR + Delhi', 'Dharampal Sir'),
    'KHARKHODA-CAPEX': ('CAPEX', 'Khushi'),
    'KOCHI-AMB-CAPEX': ('CAPEX', 'Khushi'),
    'KOCHI-AMBAL-CSR': ('KERALA', "Aswathy Ma'am"),
    'KOCHI-AMBALA': ('KERALA', "Aswathy Ma'am"),
    'KOCHI-AMBALA CS': ('KERALA', "Aswathy Ma'am"),
    'KOCHI-AMBALA-CA': ('KERALA', "Aswathy Ma'am"),
    'KOCHI-AMBALA-CS': ('KERALA', "Aswathy Ma'am"),
    'KOCHI-AMBALAMUG': ('KERALA', "Aswathy Ma'am"),
    'KOCHI-EDAYAR': ('KERALA', "Aswathy Ma'am"),
    'KOCHI-EDAYAR CS': ('KERALA', "Aswathy Ma'am"),
    'KOCHI-EDAYAR-CS': ('KERALA', "Aswathy Ma'am"),
    'KOL-1 CAPEX': ('CAPEX', 'Khushi'),
    'KOL-2-CAPEX': ('CAPEX', 'Khushi'),
    'KOL-4-CAPEX': ('CAPEX', 'Khushi'),
    'KOL-Hooghly': ('WEST BENGAL', 'Sapan Sir'),
    'KOL-TAR-CAPEX': ('CAPEX', 'Khushi'),
    'KOL-TARATALA': ('WEST BENGAL', 'Sapan Sir'),
    'KOL2-CAPEX': ('CAPEX', 'Khushi'),
    'KOL3-CAPEX': ('CAPEX', 'Khushi'),
    'KOL4-CAPEX': ('CAPEX', 'Khushi'),
    'KOLKATA': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA - 1': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA - 2': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA - 3': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA -3': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA 1': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA 2': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA 3': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA II': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA- 2': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA-1': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA-2': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA-2 CAPEX': ('CAPEX', 'Khushi'),
    'KOLKATA-2 CSR': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA-2-CAPEX': ('CAPEX', 'Khushi'),
    'KOLKATA-3': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA-3-CAPEX': ('CAPEX', 'Khushi'),
    'KOLKATA-4': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA-6': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA-I': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATA-II': ('WEST BENGAL', 'Sapan Sir'),
    'KOLKATTA-2': ('WEST BENGAL', 'Sapan Sir'),
    'KOLLUR-CAPEX': ('CAPEX', 'Khushi'),
    'KOTTAYAM-CAPEX': ('CAPEX', 'Khushi'),
    'KOTTAYAM-NA-CSR': ('KERALA', "Aswathy Ma'am"),
    'KOTTAYAM-NAT-CS': ('KERALA', "Aswathy Ma'am"),
    'KOTTAYAM-NATTAK': ('KERALA', "Aswathy Ma'am"),
    'KOZHIKOD-CAPEX': ('CAPEX', 'Khushi'),
    'KOZHIKODE': ('KERALA', "Aswathy Ma'am"),
    'KOZHIKODE-CAPEX': ('CAPEX', 'Khushi'),
    'KOZHIKODE-ELATH': ('KERALA', "Aswathy Ma'am"),
    'KURALI': ('PUNJAB', 'Mukesh Sir'),
    'KURALI - CAPEX': ('CAPEX', 'Khushi'),
    'KURALI-CAPEX': ('CAPEX', 'Khushi'),
    'Kalyani-Bypass': ('WEST BENGAL', 'Sapan Sir'),
    'Ker-Kottyam': ('KERALA', "Aswathy Ma'am"),
    'Kochi-Amb': ('KERALA', "Aswathy Ma'am"),
    'Kochi-Edyar': ('KERALA', "Aswathy Ma'am"),
    'Kochi-Edyar-2': ('KERALA', "Aswathy Ma'am"),
    'Kol-New town': ('WEST BENGAL', 'Sapan Sir'),
    'Kolkata 2-Capex': ('CAPEX', 'Khushi'),
    'Kolkata2-Capex': ('CAPEX', 'Khushi'),
    'Kolkatta 2': ('WEST BENGAL', 'Sapan Sir'),
    'L&T261 -CAPEX': ('CAPEX', 'Khushi'),
    'L&T290 -CAPEX': ('CAPEX', 'Khushi'),
    'LANKA (DALMIA)': ('ASSAM', 'Sapan Sir'),
    'LANKA -DALMIA': ('ASSAM', 'Sapan Sir'),
    'LANKA-DALMIA': ('ASSAM', 'Sapan Sir'),
    'LU1-CAPEX': ('CAPEX', 'Khushi'),
    'LU2- CAPEX': ('CAPEX', 'Khushi'),
    'LU3- CAPEX': ('CAPEX', 'Khushi'),
    'LU3-CAPEX': ('CAPEX', 'Khushi'),
    'LUCKNOW': ('UTTAR PRADESH', 'Dharampal Sir'),
    'LUCKNOW CAPEX': ('CAPEX', 'Khushi'),
    'LUCKNOW-CAPEX': ('CAPEX', 'Khushi'),
    'LUCKNOW-CSR': ('UTTAR PRADESH', 'Dharampal Sir'),
    'LUDHIANA': ('PUNJAB', 'Mukesh Sir'),
    'LUDHIANA LADOWA': ('PUNJAB', 'Mukesh Sir'),
    'LUDHIANA-1': ('PUNJAB', 'Mukesh Sir'),
    'LUDHIANA-CAPEX': ('CAPEX', 'Khushi'),
    'LUDHIANA-IRISE': ('PUNJAB', 'Mukesh Sir'),
    'LUDHIANA-LADOWA': ('PUNJAB', 'Mukesh Sir'),
    'LUDHIANA-LODOWA': ('PUNJAB', 'Mukesh Sir'),
    'LUDHIANA-PUNJAB': ('PUNJAB', 'Mukesh Sir'),
    'LUDHIANA1': ('PUNJAB', 'Mukesh Sir'),
    'LUDHIANA3': ('PUNJAB', 'Mukesh Sir'),
    'Ludhiana-2': ('PUNJAB', 'Mukesh Sir'),
    'Ludhiana-3': ('PUNJAB', 'Mukesh Sir'),
    'MANGALORE': ('MANGALORE', 'Elaiyaraja Sir'),
    'MANGALORE 1': ('MANGALORE', 'Elaiyaraja Sir'),
    'MANGALORE-01': ('MANGALORE', 'Elaiyaraja Sir'),
    'MANGALORE-1': ('MANGALORE', 'Elaiyaraja Sir'),
    'MANGALORE-CAPEX': ('CAPEX', 'Khushi'),
    'MANGALORE-CSR': ('MANGALORE', 'Elaiyaraja Sir'),
    'MANGALORE-I': ('MANGALORE', 'Elaiyaraja Sir'),
    'MANKOLI-CAPEX': ('CAPEX', 'Khushi'),
    'MIRA ROAD-CAPEX': ('CAPEX', 'Khushi'),
    'MIRA ROAD-MUMBA': ('MUMBAI', 'Haresh Sir'),
    'MIRAROAD-CAPEX': ('CAPEX', 'Khushi'),
    'MOHALI': ('PUNJAB', 'Mukesh Sir'),
    'MOHALI PUNJAB': ('PUNJAB', 'Mukesh Sir'),
    'MOHALI-1': ('PUNJAB', 'Mukesh Sir'),
    'MOHALI-2': ('PUNJAB', 'Mukesh Sir'),
    'MOHALI-CAPEX': ('CAPEX', 'Khushi'),
    'MOHALI-CSR': ('PUNJAB', 'Mukesh Sir'),
    'MOHALI-PUNJAB': ('PUNJAB', 'Mukesh Sir'),
    'MOHINI L&T': ('PUNJAB', 'Mukesh Sir'),
    'MOHINI-L&T': ('PUNJAB', 'Mukesh Sir'),
    'MOSHI-CAPEX': ('CAPEX', 'Khushi'),
    'MP-JABALPUR': ('MADHYA PRADESH', 'Makrand Sir'),
    'MP-SATNA': ('MADHYA PRADESH', 'Makrand Sir'),
    'MU-AND-CAPEX': ('CAPEX', 'Khushi'),
    'MU-SAKINAKA-CAP': ('CAPEX', 'Khushi'),
    'MUM DOMBIVALI': ('MUMBAI', 'Haresh Sir'),
    'MUM- ANDHERI': ('MUMBAI', 'Haresh Sir'),
    'MUM- DOMBIVALI': ('MUMBAI', 'Haresh Sir'),
    'MUM- GHATKOPAR': ('MUMBAI', 'Haresh Sir'),
    'MUM- MIRAROAD': ('MUMBAI', 'Haresh Sir'),
    'MUM- WADALA': ('MUMBAI', 'Haresh Sir'),
    'MUM-ANDH-CAPEX': ('CAPEX', 'Khushi'),
    'MUM-ANDHERI': ('MUMBAI', 'Haresh Sir'),
    'MUM-ANDHERI CAP': ('CAPEX', 'Khushi'),
    'MUM-ANDHERI-CAP': ('CAPEX', 'Khushi'),
    'MUM-BHOIWAD-CAP': ('CAPEX', 'Khushi'),
    'MUM-BHOIWADA': ('MUMBAI', 'Haresh Sir'),
    'MUM-BOIW-CAPEX': ('CAPEX', 'Khushi'),
    'MUM-DEONAR': ('MUMBAI', 'Haresh Sir'),
    'MUM-DOM-CAPEX': ('CAPEX', 'Khushi'),
    'MUM-DOMB-CAPEX': ('CAPEX', 'Khushi'),
    'MUM-DOMBAVALI-C': ('MUMBAI', 'Haresh Sir'),
    'MUM-DOMBI-CAPEX': ('CAPEX', 'Khushi'),
    'MUM-DOMBIVALI': ('MUMBAI', 'Haresh Sir'),
    'MUM-DOMBIVALI-C': ('MUMBAI', 'Haresh Sir'),
    'MUM-DOMBIVLI': ('MUMBAI', 'Haresh Sir'),
    'MUM-GHATKOPAR': ('MUMBAI', 'Haresh Sir'),
    'MUM-HCC': ('MUMBAI', 'Haresh Sir'),
    'MUM-HCC-CAPEX': ('CAPEX', 'Khushi'),
    'MUM-HCC-CSR': ('MUMBAI', 'Haresh Sir'),
    'MUM-HCC-WORLI': ('MUMBAI', 'Haresh Sir'),
    'MUM-HCC2-CAPEX': ('CAPEX', 'Khushi'),
    'MUM-HO-CAPEX': ('CAPEX', 'Khushi'),
    'MUM-KALYAN': ('MUMBAI', 'Haresh Sir'),
    'MUM-KASHIMIRA': ('MUMBAI', 'Haresh Sir'),
    'MUM-KASHMIRA': ('MUMBAI', 'Haresh Sir'),
    'MUM-KHALAPUR': ('MUMBAI', 'Haresh Sir'),
    'MUM-KHARGHAR': ('MUMBAI', 'Haresh Sir'),
    'MUM-MANKO-CAPEX': ('CAPEX', 'Khushi'),
    'MUM-MANKOLI': ('MUMBAI', 'Haresh Sir'),
    'MUM-MANKOLI-CSR': ('MUMBAI', 'Haresh Sir'),
    'MUM-MIRA ROAD': ('MUMBAI', 'Haresh Sir'),
    'MUM-MIRA-CAPEX': ('CAPEX', 'Khushi'),
    'MUM-MIRAROAD': ('MUMBAI', 'Haresh Sir'),
    'MUM-MR-CAPEX': ('CAPEX', 'Khushi'),
    'MUM-OBEROI': ('MUMBAI', 'Haresh Sir'),
    'MUM-REALTY-CAPE': ('CAPEX', 'Khushi'),
    'MUM-RUNAWAL': ('MUMBAI', 'Haresh Sir'),
    'MUM-RUNWAL': ('MUMBAI', 'Haresh Sir'),
    'MUM-Raheja': ('MUMBAI', 'Haresh Sir'),
    'MUM-SAKIN-CAPEX': ('CAPEX', 'Khushi'),
    'MUM-SAKINAKA': ('MUMBAI', 'Haresh Sir'),
    'MUM-SAKINAKA-CS': ('MUMBAI', 'Haresh Sir'),
    'MUM-SITALBAUG': ('MUMBAI', 'Haresh Sir'),
    'MUM-TALOJA': ('MUMBAI', 'Haresh Sir'),
    'MUM-TURBHE': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI': ('HEAD OFFICE', 'Sneha'),
    'MUMBAI - HO': ('HEAD OFFICE', 'Sneha'),
    'MUMBAI - MIRARO': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI - TRADIN': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI -TRADING': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI -TURBHE': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI DEONAR': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI DOMBIVAL': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI DOMBIVIL': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI DOMBIVLI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI GHATKOPA': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI GHATKOPE': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI HO': ('HEAD OFFICE', 'Sneha'),
    'MUMBAI HOCAPEX': ('CAPEX', 'Khushi'),
    'MUMBAI KASHIMIR': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI MANKOLI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI MIRA RD': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI MIRAROAD': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI MIRROAD': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI Sitalbau': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI TRADING': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI- ANDHERI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-1': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-ANDHARI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-ANDHERI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-DEONAR': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-DEVNAR': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-DIGHI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-DOBIVALI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-DOMBIVAL': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-GHATKOPA': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-GHATKOPE': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-GODREJ': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-HO': ('HEAD OFFICE', 'Sneha'),
    'MUMBAI-HO CAPEX': ('CAPEX', 'Khushi'),
    'MUMBAI-HO-CAPEX': ('CAPEX', 'Khushi'),
    'MUMBAI-HO-CSR': ('HEAD OFFICE', 'Sneha'),
    'MUMBAI-HO-ISD': ('HEAD OFFICE', 'Sneha'),
    'MUMBAI-KASHIMIR': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-KASHMIRA': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-KHALAPUR': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-KHARGAR': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-KHARGHAR': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-KHOPOLI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-KRAHEJA': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-MANKHOLI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-MANKOLI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-MIRA': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-MIRA RD': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-MIRA ROA': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-MIRAORD': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-MIRARAOD': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-MIRAROAD': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-OBEROI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-RUNAWAL': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-SAKINAKA': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-SAKINKA': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-SITAL BA': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-SITALBAU': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-TAL': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-TALOJ': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-TALOJA': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-TRADING': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-TURBHE': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-URAN': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-VIKHROLI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-VIKROLI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-WADALA': ('MUMBAI', 'Haresh Sir'),
    'MUMBAI-WORLI': ('MUMBAI', 'Haresh Sir'),
    'MUMBAIHO-CAPEX': ('CAPEX', 'Khushi'),
    'MUMBAIHOCAPEX': ('CAPEX', 'Khushi'),
    'MUNDRA-CAPEX': ('CAPEX', 'Khushi'),
    'MUNDWA-CAPEX': ('CAPEX', 'Khushi'),
    'MUNGALIYA-CAPEX': ('CAPEX', 'Khushi'),
    'Mohali-Derabass': ('PUNJAB', 'Mukesh Sir'),
    'Mum-Pallava': ('MUMBAI', 'Haresh Sir'),
    'Mum-Uran': ('MUMBAI', 'Haresh Sir'),
    'Mumbai - Dombiv': ('MUMBAI', 'Haresh Sir'),
    'Mumbai - Sakina': ('MUMBAI', 'Haresh Sir'),
    'Mumbai Andheri': ('MUMBAI', 'Haresh Sir'),
    'Mumbai HO-Capex': ('CAPEX', 'Khushi'),
    'Mumbai Kashmira': ('MUMBAI', 'Haresh Sir'),
    'Mumbai Mira Roa': ('MUMBAI', 'Haresh Sir'),
    'Mumbai-Airoli': ('MUMBAI', 'Haresh Sir'),
    'Mumbai-Dombiali': ('MUMBAI', 'Haresh Sir'),
    'Mumbai-HCC Worl': ('MUMBAI', 'Haresh Sir'),
    'Mumbai-Palava': ('MUMBAI', 'Haresh Sir'),
    'Mumbai-Runwal': ('MUMBAI', 'Haresh Sir'),
    'Mumbai-Sakina': ('MUMBAI', 'Haresh Sir'),
    'NA1-CAPEX': ('CAPEX', 'Khushi'),
    'NAG-CAPEX': ('CAPEX', 'Khushi'),
    'NAG1-CAPEX': ('CAPEX', 'Khushi'),
    'NAGPUR': ('NAGPUR', 'Makrand Sir'),
    'NAGPUR WARDHA': ('NAGPUR', 'Makrand Sir'),
    'NAGPUR-2': ('NAGPUR', 'Makrand Sir'),
    'NAGPUR-CAPEX': ('CAPEX', 'Khushi'),
    'NAGPUR-HIGNA': ('NAGPUR', 'Makrand Sir'),
    'NAGPUR-HINGA': ('NAGPUR', 'Makrand Sir'),
    'NAGPUR-HINGNA': ('NAGPUR', 'Makrand Sir'),
    'NAGPUR-WARDHA': ('NAGPUR', 'Makrand Sir'),
    'NAVASARI-CAPEX': ('CAPEX', 'Khushi'),
    'NAVASARI-L&T': ('GUJARAT', 'Dinesh Sir'),
    'NAVI MUMBAI': ('MUMBAI', 'Haresh Sir'),
    'NAVSARI': ('GUJARAT', 'Dinesh Sir'),
    'NAVSARI L&T': ('GUJARAT', 'Dinesh Sir'),
    'NAVSARI-CAPEX': ('CAPEX', 'Khushi'),
    'NAVSARI-L&T': ('GUJARAT', 'Dinesh Sir'),
    'NAWALGARH-CAPEX': ('CAPEX', 'Khushi'),
    'NAWALGHAR-CAPEX': ('CAPEX', 'Khushi'),
    'NCHENNAI-CAPEX': ('CAPEX', 'Khushi'),
    'NCR- Gurgaon M3': ('NCR + Delhi', 'Dharampal Sir'),
    'NCR-Gurgaon Bad': ('NCR + Delhi', 'Dharampal Sir'),
    'NCR-Gurgaon Shi': ('NCR + Delhi', 'Dharampal Sir'),
    'NEW DELHI': ('NCR + Delhi', 'Dharampal Sir'),
    'NOIDA': ('NCR + Delhi', 'Dharampal Sir'),
    'NOIDA 1': ('NCR + Delhi', 'Dharampal Sir'),
    'NOIDA-1': ('NCR + Delhi', 'Dharampal Sir'),
    'NVMUMBAI-CAPEX': ('CAPEX', 'Khushi'),
    'Nagpur 2': ('NAGPUR', 'Makrand Sir'),
    'OBEROI-CAPEX': ('CAPEX', 'Khushi'),
    'ORISSA': ('ODISHA + RANCHI', 'Manas Sir'),
    'PANAGARH-CAPEX': ('CAPEX', 'Khushi'),
    'PATNA': ('BIHAR', 'Sapan Sir'),
    'PATNA DIDARGANJ': ('BIHAR', 'Sapan Sir'),
    'PATNA MAKHDAMPU': ('BIHAR', 'Sapan Sir'),
    'PATNA-BARH': ('BIHAR', 'Sapan Sir'),
    'PATNA-BHEL': ('BIHAR', 'Sapan Sir'),
    'PATNA-CAPEX': ('CAPEX', 'Khushi'),
    'PATNA-CAPTIVE': ('BIHAR', 'Sapan Sir'),
    'PATNA-DIDAR GAN': ('BIHAR', 'Sapan Sir'),
    'PATNA-DIDARGANJ': ('BIHAR', 'Sapan Sir'),
    'PATNA-MAKDAMPU': ('BIHAR', 'Sapan Sir'),
    'PATNA-MAKDAMPUR': ('BIHAR', 'Sapan Sir'),
    'PATNA-MAKDUMPUR': ('BIHAR', 'Sapan Sir'),
    'PATNA-MAKHDAMPU': ('BIHAR', 'Sapan Sir'),
    'PATNA-MAKUDAMPU': ('BIHAR', 'Sapan Sir'),
    'PATNA1-CAPEX': ('CAPEX', 'Khushi'),
    'PU2-CAPEX': ('CAPEX', 'Khushi'),
    'PUN-TPL Metro 2': ('PUNE', 'Pramod Sir'),
    'PUN1-CAPEX': ('CAPEX', 'Khushi'),
    'PUN2-CAPEX': ('CAPEX', 'Khushi'),
    'PUN3-CAPEX': ('CAPEX', 'Khushi'),
    'PUN4-CAPEX': ('CAPEX', 'Khushi'),
    'PUN5-CAPEX': ('CAPEX', 'Khushi'),
    'PUN6-CAPEX': ('CAPEX', 'Khushi'),
    'PUNE': ('PUNE', 'Pramod Sir'),
    'PUNE - 2 CSR': ('PUNE', 'Pramod Sir'),
    'PUNE - 3 CSR': ('PUNE', 'Pramod Sir'),
    'PUNE -2': ('PUNE', 'Pramod Sir'),
    'PUNE -4': ('PUNE', 'Pramod Sir'),
    'PUNE 1': ('PUNE', 'Pramod Sir'),
    'PUNE 2': ('PUNE', 'Pramod Sir'),
    'PUNE 3': ('PUNE', 'Pramod Sir'),
    'PUNE 4': ('PUNE', 'Pramod Sir'),
    'PUNE II': ('PUNE', 'Pramod Sir'),
    'PUNE TATA': ('PUNE', 'Pramod Sir'),
    'PUNE TATA CAPEX': ('CAPEX', 'Khushi'),
    'PUNE TATA-CAPEX': ('CAPEX', 'Khushi'),
    'PUNE VADGAON': ('PUNE', 'Pramod Sir'),
    'PUNE VADGAON CA': ('PUNE', 'Pramod Sir'),
    'PUNE VADGAON-CA': ('PUNE', 'Pramod Sir'),
    'PUNE-1': ('PUNE', 'Pramod Sir'),
    'PUNE-1 CSR': ('PUNE', 'Pramod Sir'),
    'PUNE-1-CAPEX': ('CAPEX', 'Khushi'),
    'PUNE-10': ('PUNE', 'Pramod Sir'),
    'PUNE-2': ('PUNE', 'Pramod Sir'),
    'PUNE-2 CSR': ('PUNE', 'Pramod Sir'),
    'PUNE-2-CAPEX': ('CAPEX', 'Khushi'),
    'PUNE-2-CSR': ('PUNE', 'Pramod Sir'),
    'PUNE-3': ('PUNE', 'Pramod Sir'),
    'PUNE-3 CSR': ('PUNE', 'Pramod Sir'),
    'PUNE-3-CAPEX': ('CAPEX', 'Khushi'),
    'PUNE-3-CSR': ('PUNE', 'Pramod Sir'),
    'PUNE-4': ('PUNE', 'Pramod Sir'),
    'PUNE-4 CSR': ('PUNE', 'Pramod Sir'),
    'PUNE-4-CAPEX': ('CAPEX', 'Khushi'),
    'PUNE-4-CSR': ('PUNE', 'Pramod Sir'),
    'PUNE-5': ('PUNE', 'Pramod Sir'),
    'PUNE-6': ('PUNE', 'Pramod Sir'),
    'PUNE-6 CAPEX': ('CAPEX', 'Khushi'),
    'PUNE-6-CAPEX': ('CAPEX', 'Khushi'),
    'PUNE-7': ('PUNE', 'Pramod Sir'),
    'PUNE-7 CSR': ('PUNE', 'Pramod Sir'),
    'PUNE-8': ('PUNE', 'Pramod Sir'),
    'PUNE-9': ('PUNE', 'Pramod Sir'),
    'PUNE-I': ('PUNE', 'Pramod Sir'),
    'PUNE-II': ('PUNE', 'Pramod Sir'),
    'PUNE-SINHGARH': ('PUNE', 'Pramod Sir'),
    'PUNE1-CAPEX': ('CAPEX', 'Khushi'),
    'PUNE2-CAPEX': ('CAPEX', 'Khushi'),
    'PUNE3-CAPEX': ('CAPEX', 'Khushi'),
    'PUNE4-CAPEX': ('CAPEX', 'Khushi'),
    'PUNE5-CAPEX': ('CAPEX', 'Khushi'),
    'PUNE6-CAPEX': ('CAPEX', 'Khushi'),
    'PUNELODHA-CAPEX': ('CAPEX', 'Khushi'),
    'PUNJAB': ('PUNJAB', 'Mukesh Sir'),
    'Patna Makhdumpu': ('BIHAR', 'Sapan Sir'),
    'Patna-Makhdumpu': ('BIHAR', 'Sapan Sir'),
    'Pun-Jambhe': ('PUNE', 'Pramod Sir'),
    'Pun-Moshi': ('PUNE', 'Pramod Sir'),
    'Pune 1-Capex': ('CAPEX', 'Khushi'),
    'Pune-1-CSR': ('PUNE', 'Pramod Sir'),
    'Pune-Lodha': ('PUNE', 'Pramod Sir'),
    'RAHEJA-CAPEX': ('CAPEX', 'Khushi'),
    'RAHEJA-MUMBAI': ('MUMBAI', 'Haresh Sir'),
    'RAIPUR': ('CHHATTISGARH', 'Makrand Sir'),
    'RAIPUR CAPEX': ('CAPEX', 'Khushi'),
    'RAIPUR SERIKHED': ('CHHATTISGARH', 'Makrand Sir'),
    'RAIPUR-2': ('CHHATTISGARH', 'Makrand Sir'),
    'RAIPUR-CAPEX': ('CAPEX', 'Khushi'),
    'RAIPUR2-CAPEX': ('CAPEX', 'Khushi'),
    'RANCHI': ('ODISHA + RANCHI', 'Manas Sir'),
    'RANCHI NAGRI': ('ODISHA + RANCHI', 'Manas Sir'),
    'RANCHI-CAPEX': ('CAPEX', 'Khushi'),
    'RANCHI-NAGRI': ('ODISHA + RANCHI', 'Manas Sir'),
    'RANIKHEDA-CAPEX': ('CAPEX', 'Khushi'),
    'RANIKHERA-CAPEX': ('CAPEX', 'Khushi'),
    'RELIANCE-JAMNAG': ('GUJARAT', 'Dinesh Sir'),
    'RUNWAL-CAPEX': ('CAPEX', 'Khushi'),
    'RUSSEL-CAPEX': ('CAPEX', 'Khushi'),
    'Raipur-Serikhed': ('CHHATTISGARH', 'Makrand Sir'),
    'SACHIN-CAPEX': ('CAPEX', 'Khushi'),
    'SAG-KOL-CAPEX': ('CAPEX', 'Khushi'),
    'SAGARDIGHI': ('WEST BENGAL', 'Sapan Sir'),
    'SAGARDIGHI CAPE': ('CAPEX', 'Khushi'),
    'SAGARDIGHI- CAP': ('CAPEX', 'Khushi'),
    'SAGARDIGHI-BHEL': ('WEST BENGAL', 'Sapan Sir'),
    'SAGARDIGHI-CAP': ('CAPEX', 'Khushi'),
    'SAGARDIGHI-CAPE': ('CAPEX', 'Khushi'),
    'SAGARDIGHI-GDCL': ('WEST BENGAL', 'Sapan Sir'),
    'SAGARDIGHICAPEX': ('CAPEX', 'Khushi'),
    'SAGARDIGI-CAPEX': ('CAPEX', 'Khushi'),
    'SAKINAKA-CAPEX': ('CAPEX', 'Khushi'),
    'SAMBHAJI NAGAR': ('SAMBHAJI NAGAR', 'Pramod Sir'),
    'SAMBHAJI-CAPEX': ('CAPEX', 'Khushi'),
    'SAMBHAJINAGAR': ('SAMBHAJI NAGAR', 'Pramod Sir'),
    'SANAND-CAPEX': ('CAPEX', 'Khushi'),
    'SASTHAVATAM-CAP': ('CAPEX', 'Khushi'),
    'SASTHAVATM-CAPE': ('CAPEX', 'Khushi'),
    'SATNA-CAPEX': ('CAPEX', 'Khushi'),
    'SATNA-KEC': ('MADHYA PRADESH', 'Makrand Sir'),
    'SATTVA-CAPEX': ('CAPEX', 'Khushi'),
    'SHIKOHPUR': ('NCR + Delhi', 'Dharampal Sir'),
    'SINHGARH-CAPEX': ('CAPEX', 'Khushi'),
    'SITALBAUG-CAPEX': ('CAPEX', 'Khushi'),
    'SITAMMA-CAPEX': ('CAPEX', 'Khushi'),
    'STARCON-CAPEX': ('CAPEX', 'Khushi'),
    'SURAT GULERMARK': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-CAPEX': ('CAPEX', 'Khushi'),
    'SURAT-GULERMAK': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-HAZIRA': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-ICCHAPORE': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-ICCHAPUR': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-ICHHAPORE': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-ICHHAPUR': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-ICHHPUR': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-ITD': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-ITD HAZIR': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-ITD-HAZIR': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-L&T': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-SACHIN': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-SUNVALI': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-SUNVALI H': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-VADODARA': ('GUJARAT', 'Dinesh Sir'),
    'SURAT-VBADODARA': ('GUJARAT', 'Dinesh Sir'),
    'SURATGULERMAK': ('GUJARAT', 'Dinesh Sir'),
    'Satna': ('MADHYA PRADESH', 'Makrand Sir'),
    'Surat-Vapi': ('GUJARAT', 'Dinesh Sir'),
    'TACLHERCAPEX': ('CAPEX', 'Khushi'),
    'TALCHAR-CAPEX': ('CAPEX', 'Khushi'),
    'TALCHER': ('ODISHA + RANCHI', 'Manas Sir'),
    'TALCHER-2': ('ODISHA + RANCHI', 'Manas Sir'),
    'TALCHER-BHEL': ('ODISHA + RANCHI', 'Manas Sir'),
    'TALCHER-CAP': ('CAPEX', 'Khushi'),
    'TALCHER-CAPE': ('CAPEX', 'Khushi'),
    'TALCHER-CAPEX': ('CAPEX', 'Khushi'),
    'TALCHER-TEKNOW': ('ODISHA + RANCHI', 'Manas Sir'),
    'TALCHER-TP': ('ODISHA + RANCHI', 'Manas Sir'),
    'TALCHER-TPL': ('ODISHA + RANCHI', 'Manas Sir'),
    'TALCHERCAPEX': ('CAPEX', 'Khushi'),
    'TALOJA-CAPEX': ('CAPEX', 'Khushi'),
    'TARA-KOL-CAPEX': ('CAPEX', 'Khushi'),
    'TARATALA-CAPEX': ('CAPEX', 'Khushi'),
    'TARATALACAPEX': ('CAPEX', 'Khushi'),
    'TATASTEEL-CAPEX': ('CAPEX', 'Khushi'),
    'TEKNOW-CAPEX': ('CAPEX', 'Khushi'),
    'TELANGANA-CAPEX': ('CAPEX', 'Khushi'),
    'THRISSUR': ('KERALA', "Aswathy Ma'am"),
    'THRISSUR-CAPEX': ('CAPEX', 'Khushi'),
    'TN-Trichy': ('KERALA', "Aswathy Ma'am"),
    'TRICHY': ('COIMBATORE + TRICHY', 'Sulaiman Sir'),
    'TRICHY-CAPEX': ('CAPEX', 'Khushi'),
    'TRIVANDRAM-CAPE': ('CAPEX', 'Khushi'),
    'TRIVANDRUM-1CAP': ('CAPEX', 'Khushi'),
    'TRIVANDRUM-2CAP': ('CAPEX', 'Khushi'),
    'TRIVENDRUM-CAPE': ('CAPEX', 'Khushi'),
    'TRVMSASTHA-CAPE': ('CAPEX', 'Khushi'),
    'TSR-GRYR-CAPEX': ('CAPEX', 'Khushi'),
    'TSR-GURUVAYR': ('KERALA', "Aswathy Ma'am"),
    'TSR-GURUVAYUR': ('KERALA', "Aswathy Ma'am"),
    'TSR-VEL-CSR': ('KERALA', "Aswathy Ma'am"),
    'TSR-VELA-CAPEX': ('CAPEX', 'Khushi'),
    'TSR-VELAKKO-CSR': ('KERALA', "Aswathy Ma'am"),
    'TSR-VELAKKODE': ('KERALA', "Aswathy Ma'am"),
    'TSR-VELAKKODE-C': ('KERALA', "Aswathy Ma'am"),
    'TSR-VELAKODE': ('KERALA', "Aswathy Ma'am"),
    'TSR-VELAKODE-CS': ('KERALA', "Aswathy Ma'am"),
    'TURBHE-CAPEX': ('CAPEX', 'Khushi'),
    'TV3-CAPEX': ('CAPEX', 'Khushi'),
    'TVM-RUSSEL': ('KERALA', "Aswathy Ma'am"),
    'TVM-RUSSEL-CSR': ('KERALA', "Aswathy Ma'am"),
    'TVM-RUSSELP': ('KERALA', "Aswathy Ma'am"),
    'TVM-SAS-CSR': ('KERALA', "Aswathy Ma'am"),
    'TVM-SASTHA': ('KERALA', "Aswathy Ma'am"),
    'TVM-SASTHA-CSR': ('KERALA', "Aswathy Ma'am"),
    'TVM-STARCON': ('KERALA', "Aswathy Ma'am"),
    'TVM2-CAPEX': ('CAPEX', 'Khushi'),
    'TVM_RUSS_CSR': ('KERALA', "Aswathy Ma'am"),
    'TVM_SASTHA': ('KERALA', "Aswathy Ma'am"),
    'TVM_STARCON': ('KERALA', "Aswathy Ma'am"),
    'UMRANGSHU': ('ASSAM', 'Sapan Sir'),
    'UMRANGSHU-ASSAM': ('ASSAM', 'Sapan Sir'),
    'UMRANGSHU-CAPEX': ('CAPEX', 'Khushi'),
    'UMRANGSHU-DALMI': ('ASSAM', 'Sapan Sir'),
    'UP-Ayodhya': ('UTTAR PRADESH', 'Dharampal Sir'),
    'UP-Gorakhpur': ('UTTAR PRADESH', 'Dharampal Sir'),
    'URAN-CAPEX': ('CAPEX', 'Khushi'),
    'Umrangso-Dalmia': ('ASSAM', 'Sapan Sir'),
    'VADODARA L&T': ('GUJARAT', 'Dinesh Sir'),
    'VADODARA-CAPEX': ('CAPEX', 'Khushi'),
    'VADODARA-DUMAD': ('GUJARAT', 'Dinesh Sir'),
    'VADODARA-L&T': ('GUJARAT', 'Dinesh Sir'),
    'VAPI-CAPEX': ('CAPEX', 'Khushi'),
    'VASAVI-CAPEX': ('CAPEX', 'Khushi'),
    'VERNA-CAPEX': ('CAPEX', 'Khushi'),
    'VI3-CAPEX': ('CAPEX', 'Khushi'),
    'VIJAYAWADA-1': ('ANDHRA PRADESH', 'Rajesh Sir'),
    'VIJAYAWADA-CAPE': ('CAPEX', 'Khushi'),
    'VIJAYWADA': ('ANDHRA PRADESH', 'Rajesh Sir'),
    'VIKROLI-CAPEX': ('CAPEX', 'Khushi'),
    'VINTA-CAPEX': ('CAPEX', 'Khushi'),
    'VIZAG': ('VIZAG', 'Rajesh Sir'),
    'VIZAG - 2': ('VIZAG', 'Rajesh Sir'),
    'VIZAG-1': ('VIZAG', 'Rajesh Sir'),
    'VIZAG-2': ('VIZAG', 'Rajesh Sir'),
    'VIZAG-2 CAPEX': ('CAPEX', 'Khushi'),
    'VIZAG-CAPEX': ('CAPEX', 'Khushi'),
    'Vadodara': ('GUJARAT', 'Dinesh Sir'),
    'Vadodara- L&T': ('GUJARAT', 'Dinesh Sir'),
    'Vapi-Gujarat': ('GUJARAT', 'Dinesh Sir'),
    'Vijayawada': ('ANDHRA PRADESH', 'Rajesh Sir'),
    'Vijayawada- Man': ('ANDHRA PRADESH', 'Rajesh Sir'),
    'Vizag-Madhurawa': ('VIZAG', 'Rajesh Sir'),
    'WARDHA-CAPEX': ('CAPEX', 'Khushi'),
    'WARDHA-NAGPUR': ('NAGPUR', 'Makrand Sir'),
    'WAYANAD - CAPEX': ('CAPEX', 'Khushi'),
    'WAYANAD CAPEX': ('CAPEX', 'Khushi'),
    'WAYANAD-CAPEX': ('CAPEX', 'Khushi'),
    'WAYANAD-KR-CAPE': ('KERALA', "Aswathy Ma'am"),
    'WAYANAD-KRISH': ('KERALA', "Aswathy Ma'am"),
    'WAYANAD-KRISHN': ('KERALA', "Aswathy Ma'am"),
    'WAYANAD-SULBTRY': ('KERALA', "Aswathy Ma'am"),
    'Wayanad': ('KERALA', "Aswathy Ma'am"),
    'DELHI\xa0 GHEVRA': ('NCR + Delhi', 'Dharampal Sir'),
}


